# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-29 19:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('quick_app', '0003_mechanic_locations'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topics', models.CharField(max_length=50)),
                ('detail', models.CharField(max_length=50)),
                ('date_joined', models.DateField()),
                ('mechanic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quick_app.Mechanic')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='locations',
            field=models.CharField(default=datetime.datetime(2017, 4, 29, 19, 30, 2, 963000, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quick_app.User'),
        ),
    ]
