# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-29 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quick_app', '0005_auto_20170430_0253'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_read',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notification',
            name='to_user',
            field=models.CharField(max_length=50),
        ),
    ]
