# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-05-05 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quick_app', '0008_auto_20170501_0209'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechanic',
            name='username',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
