# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-05-09 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quick_app', '0011_auto_20170507_1837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='date_joined',
        ),
        migrations.AddField(
            model_name='job',
            name='date',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='locations',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='time',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
