# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-05-09 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quick_app', '0012_auto_20170509_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='mechanic',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='job',
            name='user',
            field=models.CharField(max_length=50),
        ),
    ]
