# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-05-10 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quick_app', '0013_auto_20170510_0349'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='place',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='price',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
