# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-05-10 22:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quick_app', '0014_auto_20170511_0245'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='topics',
            new_name='list_detail',
        ),
    ]
