# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-05-12 07:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quick_app', '0015_auto_20170511_0513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='notification',
        ),
    ]
