# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-05-12 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quick_app', '0016_remove_user_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='car_detail',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
